
# nohup java -jar -Dspring.profiles.active=prod -Xms500m -Xmx500m -Xss256k -XX:+HeapDumpOnOutOfMemoryError /data/service/order/web-controller-1.0.0-SNAPSHOT.jar >> /data/weblog/order/jb.log 2>&1 &
# tail -f /data/weblog/order/jb.log


# nohup java -jar -Dspring.profiles.active=prod -Xms3072m -Xmx3072m -Xss256k -XX:+HeapDumpOnOutOfMemoryError /data/service/backend/web-controller-1.0.0-SNAPSHOT.jar >> /data/service/backend/jb.log 2>&1 &
